-- Vendor names saved as web addresses before names were normalized ("thethriftybot.com",
-- "www.mcmaster.com") become the names new requests use ("The Thrifty Bot", "McMaster-Carr"),
-- so each vendor groups and matches as one. Same list as src/lib/vendors.ts.
UPDATE order_requests SET vendor = CASE lower(trim(CASE WHEN lower(trim(vendor)) LIKE 'www.%' THEN substr(trim(vendor), 5) ELSE trim(vendor) END))
  WHEN 'amazon.com' THEN 'Amazon'
  WHEN 'a.co' THEN 'Amazon'
  WHEN 'amzn.to' THEN 'Amazon'
  WHEN 'mcmaster.com' THEN 'McMaster-Carr'
  WHEN 'digikey.com' THEN 'Digikey'
  WHEN 'wcproducts.com' THEN 'West Coast Products'
  WHEN 'revrobotics.com' THEN 'REV Robotics'
  WHEN 'thethriftybot.com' THEN 'The Thrifty Bot'
  WHEN 'andymark.com' THEN 'AndyMark'
  WHEN 'swervedrivespecialties.com' THEN 'Swerve Drive Specialties'
  WHEN 'ctr-electronics.com' THEN 'CTR Electronics'
  WHEN 'store.ctr-electronics.com' THEN 'CTR Electronics'
  WHEN 'homedepot.com' THEN 'Home Depot'
  WHEN 'lowes.com' THEN 'Lowe''s'
  WHEN 'acehardware.com' THEN 'Ace Hardware'
  WHEN 'ebay.com' THEN 'eBay'
  WHEN 'ebay.io' THEN 'eBay'
  WHEN 'powerwerx.com' THEN 'Powerwerx'
  WHEN 'onlinemetals.com' THEN 'Online Metals'
  WHEN 'vbeltguys.com' THEN 'V-Belt Guys'
  WHEN 'bambulab.com' THEN 'Bambu Lab'
  WHEN 'us.store.bambulab.com' THEN 'Bambu Lab'
  WHEN 'easyrulerplastic.com' THEN 'EasyRuler Plastic'
  WHEN 'tekton.com' THEN 'TEKTON'
  WHEN 'walmart.com' THEN 'Walmart'
END
WHERE lower(trim(CASE WHEN lower(trim(vendor)) LIKE 'www.%' THEN substr(trim(vendor), 5) ELSE trim(vendor) END)) IN ('amazon.com', 'a.co', 'amzn.to', 'mcmaster.com', 'digikey.com', 'wcproducts.com', 'revrobotics.com', 'thethriftybot.com', 'andymark.com', 'swervedrivespecialties.com', 'ctr-electronics.com', 'store.ctr-electronics.com', 'homedepot.com', 'lowes.com', 'acehardware.com', 'ebay.com', 'ebay.io', 'powerwerx.com', 'onlinemetals.com', 'vbeltguys.com', 'bambulab.com', 'us.store.bambulab.com', 'easyrulerplastic.com', 'tekton.com', 'walmart.com');

UPDATE vendor_orders SET vendor = CASE lower(trim(CASE WHEN lower(trim(vendor)) LIKE 'www.%' THEN substr(trim(vendor), 5) ELSE trim(vendor) END))
  WHEN 'amazon.com' THEN 'Amazon'
  WHEN 'a.co' THEN 'Amazon'
  WHEN 'amzn.to' THEN 'Amazon'
  WHEN 'mcmaster.com' THEN 'McMaster-Carr'
  WHEN 'digikey.com' THEN 'Digikey'
  WHEN 'wcproducts.com' THEN 'West Coast Products'
  WHEN 'revrobotics.com' THEN 'REV Robotics'
  WHEN 'thethriftybot.com' THEN 'The Thrifty Bot'
  WHEN 'andymark.com' THEN 'AndyMark'
  WHEN 'swervedrivespecialties.com' THEN 'Swerve Drive Specialties'
  WHEN 'ctr-electronics.com' THEN 'CTR Electronics'
  WHEN 'store.ctr-electronics.com' THEN 'CTR Electronics'
  WHEN 'homedepot.com' THEN 'Home Depot'
  WHEN 'lowes.com' THEN 'Lowe''s'
  WHEN 'acehardware.com' THEN 'Ace Hardware'
  WHEN 'ebay.com' THEN 'eBay'
  WHEN 'ebay.io' THEN 'eBay'
  WHEN 'powerwerx.com' THEN 'Powerwerx'
  WHEN 'onlinemetals.com' THEN 'Online Metals'
  WHEN 'vbeltguys.com' THEN 'V-Belt Guys'
  WHEN 'bambulab.com' THEN 'Bambu Lab'
  WHEN 'us.store.bambulab.com' THEN 'Bambu Lab'
  WHEN 'easyrulerplastic.com' THEN 'EasyRuler Plastic'
  WHEN 'tekton.com' THEN 'TEKTON'
  WHEN 'walmart.com' THEN 'Walmart'
END
WHERE lower(trim(CASE WHEN lower(trim(vendor)) LIKE 'www.%' THEN substr(trim(vendor), 5) ELSE trim(vendor) END)) IN ('amazon.com', 'a.co', 'amzn.to', 'mcmaster.com', 'digikey.com', 'wcproducts.com', 'revrobotics.com', 'thethriftybot.com', 'andymark.com', 'swervedrivespecialties.com', 'ctr-electronics.com', 'store.ctr-electronics.com', 'homedepot.com', 'lowes.com', 'acehardware.com', 'ebay.com', 'ebay.io', 'powerwerx.com', 'onlinemetals.com', 'vbeltguys.com', 'bambulab.com', 'us.store.bambulab.com', 'easyrulerplastic.com', 'tekton.com', 'walmart.com');
