-- Generated by workers/orders/scripts/catalog-stock-lengths.py: stock material (shafts, tube,
-- spline, extrusion) loses the FRCDesign CAD length and gets the length vendors sell, or none
-- when they sell several. Only items still as seeded change, matched by FRCDesign record id.
-- WCP-0543: 10DP Gear Rack (35.5" L, #10-32 Clearance)
UPDATE catalog_items SET name = '10 DP Gear Rack (#10-32 Clearance)', options = '{"Type": "10 DP", "Length": "35.5\""}' WHERE source_id = 'ae49473a-88ce-46f6-b7f0-5914d8e3739e:7152823111e0' AND name = '10 DP Gear Rack (#10-32 Clearance)' AND options = '{"Type": "10 DP", "Length": "1 inch"}';
-- WCP-0291: 20DP Gear Rack (35.5" L, #10-32 Clearance)
UPDATE catalog_items SET name = '20 DP Gear Rack (#10-32 Clearance)', options = '{"Type": "20 DP", "Length": "35.5\""}' WHERE source_id = 'ae49473a-88ce-46f6-b7f0-5914d8e3739e:d2fdad30acb5' AND name = '20 DP Gear Rack (#10-32 Clearance)' AND options = '{"Type": "20 DP", "Length": "1 inch"}';
-- REV-21-3207: Aluminum Angle - 0.74in x 0.74in - 47in 
UPDATE catalog_items SET name = '0.74" x 0.74" x 0.125" Aluminum Angle (47" L, 0.5" Pitch Hole Pattern)', options = '{"Type": "0.74\" x 0.74\" x 0.125\"", "Hole Offset": "0.5 inch", "Length": "47\""}' WHERE source_id = '5ae31e07-6fb2-46b9-aa5b-70d30b3429ec:e00b8854d635' AND name = '0.74" x 0.74" x 0.125" Aluminum Angle (2" L, 0.5" Pitch Hole Pattern)' AND options = '{"Type": "0.74\" x 0.74\" x 0.125\"", "Length": "2 inch", "Hole Offset": "0.5 inch"}';
-- WCP-0929: 1" x 1" x 2.5mm Aluminum Angle with Hole Pattern (47")
UPDATE catalog_items SET name = '1" x 1" x 0.090" Aluminum Angle (47" L, 0.5" Pitch Hole Pattern)', options = '{"Type": "1\" x 1\" x 0.090\"", "Hole Offset": "0.5 inch", "Length": "47\""}' WHERE source_id = 'c95422a7-5e50-4505-b552-37f4e93ecf88:53dd950a066f' AND name = '1" x 1" x 0.090" Aluminum Angle (2" L, 0.5" Pitch Hole Pattern)' AND options = '{"Type": "1\" x 1\" x 0.090\"", "Length": "2 inch", "Hole Offset": "0.5 inch"}';
-- WCP-0930: 2" x 2" x 2.5mm Aluminum Angle with Hole Pattern (47")
UPDATE catalog_items SET name = '2" x 2" x 0.090" Aluminum Angle (47" L, 0.5" Pitch Hole Pattern)', options = '{"Type": "2\" x 2\" x 0.090\"", "Hole Offset": "0.5 inch", "Length": "47\""}' WHERE source_id = 'c95422a7-5e50-4505-b552-37f4e93ecf88:400c066382fa' AND name = '2" x 2" x 0.090" Aluminum Angle (2" L, 0.5" Pitch Hole Pattern)' AND options = '{"Type": "2\" x 2\" x 0.090\"", "Length": "2 inch", "Hole Offset": "0.5 inch"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '1" x 1" MAXTube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1\" x 1\" w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:5506577971d4' AND name = '1" x 1" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1\" x 1\" w/ Grid Pattern"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '1/2" x 1/2" x 0.0625" MAXTube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1/2\" x 1/2\" x 0.0625\" w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:bfbb3cb812d7' AND name = '1/2" x 1/2" x 0.0625" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1/2\" x 1/2\" x 0.0625\" w/ Grid Pattern"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '1" x 1" x 0.0625" MAXTube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1\" x 1\" x 0.0625\" w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:54cbe49d05a6' AND name = '1" x 1" x 0.0625" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1\" x 1\" x 0.0625\" w/ Grid Pattern"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '1" x 1" x 0.125" MAXTube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1\" x 1\" x 0.125\" w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:cdd68fa13d76' AND name = '1" x 1" x 0.125" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1\" x 1\" x 0.125\" w/ Grid Pattern"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" x 0.0625" MAXTube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.0625\" w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:2cfeb12ee33b' AND name = '2" x 1" x 0.0625" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.0625\" w/ Grid Pattern"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" x 0.125" MAXTube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.125\" w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:982f98abcc63' AND name = '2" x 1" x 0.125" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.125\" w/ Grid Pattern"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" x 0.1875" MAXTube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.1875\" w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:8532e994819f' AND name = '2" x 1" x 0.1875" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.1875\" w/ Grid Pattern"}';
-- REV-21-2162: MAXTube - 2x1 MAXTube - 2x1 - 47in (REV-21-2162)
UPDATE catalog_items SET name = '2" x 1" MAXTube (47" L, Top Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" Normal"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:9dc7eb62bb47' AND name = '2" x 1" MAXTube (3" L, Top Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" Normal"}';
-- REV-21-2590: no vendor listing
UPDATE catalog_items SET name = '2" x 1" MAXTube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" Normal w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:a0a6dec53178' AND name = '2" x 1" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" Normal w/ Grid Pattern"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" MAXTube (MAX Pattern)', options = '{"Tube Type": "2\" x 1\" Normal w/ MAX Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:3b6970991739' AND name = '2" x 1" MAXTube (3" L, MAX Pattern)' AND options = '{"Tube Type": "2\" x 1\" Normal w/ MAX Pattern"}';
-- REV-21-2161: MAXTube - 2x1 MAXTube - 2x1 - Light - 47in (REV-21-2161)
UPDATE catalog_items SET name = '2" x 1" Light MAXTube (47" L, Top Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" Light"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:8bba373a4f0d' AND name = '2" x 1" Light MAXTube (3" L, Top Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" Light"}';
-- REV-21-2161: MAXTube - 2x1 MAXTube - 2x1 - Light - 47in (REV-21-2161)
UPDATE catalog_items SET name = '2" x 1" Light MAXTube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" Light w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:fd12fbd5eabe' AND name = '2" x 1" Light MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" Light w/ Grid Pattern"}';
-- REV-21-3288: MAXTube - 2x2 MAXTube - 2x2 with Grid Pattern 4-Sides - 47in (REV-21-3288)
UPDATE catalog_items SET name = '2" x 2" MAXTube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 2\" w/ Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:8d9ad6a85343' AND name = '2" x 2" MAXTube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 2\" w/ Grid Pattern"}';
-- REV-21-3286: MAXTube - 2x2 MAXTube - 2x2 with MAX Pattern 4-Sides - 47in (REV-21-3286)
UPDATE catalog_items SET name = '2" x 2" MAXTube (47" L, MAX Pattern)', options = '{"Tube Type": "2\" x 2\" w/ MAX Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:0d5339829195' AND name = '2" x 2" MAXTube (3" L, MAX Pattern)' AND options = '{"Tube Type": "2\" x 2\" w/ MAX Pattern"}';
-- REV-21-3287: MAXTube - 2x2 MAXTube - 2x2 with MAX and Grid Pattern - 47in (REV-21-3287)
UPDATE catalog_items SET name = '2" x 2" MAXTube (47" L, MAX and Grid Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 2\" w/ MAX & Grid Pattern"}' WHERE source_id = '9a23c6c4-96df-4f6a-ae06-02879c065454:117490261b3a' AND name = '2" x 2" MAXTube (3" L, MAX and Grid Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 2\" w/ MAX & Grid Pattern"}';
-- am-5179: 47 in. Pre-Drilled Aluminium Box Tube 2 in. x 1 in. / 1/16 in. / 4 Faces
UPDATE catalog_items SET name = '2" x 1" x 0.0625" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.0625\"", "Pattern Type": "Full"}' WHERE source_id = 'd93be179-f4bd-4424-88cb-98f701447642:74693ed83fed' AND name = '2" x 1" x 0.0625" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.0625\"", "Pattern Type": "Full"}';
-- am-5177: 47 in. Pre-Drilled Aluminium Box Tube 1 in. x 1 in. / 1/16 in. / 4 Faces
UPDATE catalog_items SET name = '1" x 1" x 0.0625" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1\" x 1\" x 0.0625\"", "Pattern Type": "Full"}' WHERE source_id = 'd93be179-f4bd-4424-88cb-98f701447642:975d174ba3cd' AND name = '1" x 1" x 0.0625" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1\" x 1\" x 0.0625\"", "Pattern Type": "Full"}';
-- am-4203: no vendor listing
UPDATE catalog_items SET name = '1" x 1" x 0.0625" Aluminum Box Tube (No Pattern)', options = '{"Tube Type": "1\" x 1\" x 0.0625\"", "Pattern Type": "None"}' WHERE source_id = 'd93be179-f4bd-4424-88cb-98f701447642:e81e30a8c342' AND name = '1" x 1" x 0.0625" Aluminum Box Tube (3" L, No Pattern)' AND options = '{"Tube Type": "1\" x 1\" x 0.0625\"", "Pattern Type": "None"}';
-- am-5178: 47 in. Pre-Drilled Aluminium Box Tube 1 in. x 1 in. / 1/8 in. / 4 Faces
UPDATE catalog_items SET name = '1" x 1" x 0.125" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1\" x 1\" x 0.125\"", "Pattern Type": "Full"}' WHERE source_id = 'd93be179-f4bd-4424-88cb-98f701447642:d0c6361aa3bd' AND name = '1" x 1" x 0.125" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1\" x 1\" x 0.125\"", "Pattern Type": "Full"}';
-- am-4204: no vendor listing
UPDATE catalog_items SET name = '1" x 1" x 0.125" Aluminum Box Tube (No Pattern)', options = '{"Tube Type": "1\" x 1\" x 0.125\"", "Pattern Type": "None"}' WHERE source_id = 'd93be179-f4bd-4424-88cb-98f701447642:add418d0c40c' AND name = '1" x 1" x 0.125" Aluminum Box Tube (3" L, No Pattern)' AND options = '{"Tube Type": "1\" x 1\" x 0.125\"", "Pattern Type": "None"}';
-- am-3214: no vendor listing
UPDATE catalog_items SET name = '2" x 1" x 0.0625" Aluminum Box Tube (No Pattern)', options = '{"Tube Type": "2\" x 1\" x 0.0625\"", "Pattern Type": "None"}' WHERE source_id = 'd93be179-f4bd-4424-88cb-98f701447642:7d9c4e987643' AND name = '2" x 1" x 0.0625" Aluminum Box Tube (3" L, No Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 0.0625\"", "Pattern Type": "None"}';
-- am-5180: 47 in. Pre-Drilled Aluminium Box Tube 2 in. x 1 in. / 1/8 in. / 4 Faces
UPDATE catalog_items SET name = '2" x 1" x 0.125" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Pattern Type": "Full"}' WHERE source_id = 'd93be179-f4bd-4424-88cb-98f701447642:c522f01e14e4' AND name = '2" x 1" x 0.125" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Pattern Type": "Full"}';
-- am-4205: no vendor listing
UPDATE catalog_items SET name = '2" x 1" x 0.125" Aluminum Box Tube (No Pattern)', options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Pattern Type": "None"}' WHERE source_id = 'd93be179-f4bd-4424-88cb-98f701447642:990e4a5f39fa' AND name = '2" x 1" x 0.125" Aluminum Box Tube (3" L, No Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Pattern Type": "None"}';
-- 240114: Patterned Tubes 47 x 2 x 1 x 0625
UPDATE catalog_items SET name = '2" x 1" x 0.0625" Aluminum Box Tube (Full Pattern, 0.5" Pitch)', options = '{"Hole Offset": "0.5 inch"}' WHERE source_id = 'f7299ed8-ea72-4082-8cdf-3d30bcd0e6c1:939e18725155' AND name = '2" x 1" x 0.0625" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Hole Offset": "0.5 inch", "Length": "3 inch"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" SWYFT Tube (1/16" Walls, Grid Pattern)', options = '{"Tube Type": "2\" x 1\" x 1/16\"", "Pattern": "Grid"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:5506577971d4' AND name = '2" x 1" SWYFT Tube (3,0 " L, 1/16" Walls, Grid Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 1/16\"", "Pattern": "Grid"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '1" x 1" SWYFT Tube (1/16" Walls, Grid Pattern)', options = '{"Tube Type": "1\" x 1\" x 1/16\"", "Pattern": "Grid"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:8c4b68f8306b' AND name = '1" x 1" SWYFT Tube (3,0 " L, 1/16" Walls, Grid Pattern)' AND options = '{"Tube Type": "1\" x 1\" x 1/16\"", "Pattern": "Grid"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '1" x 1" SWYFT Tube (1/8" Walls, Grid Pattern)', options = '{"Tube Type": "1\" x 1\" x 1/8\"", "Pattern": "Grid"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:a2a3692f2cff' AND name = '1" x 1" SWYFT Tube (3,0 " L, 1/8" Walls, Grid Pattern)' AND options = '{"Tube Type": "1\" x 1\" x 1/8\"", "Pattern": "Grid"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" SWYFT Tube (0.035" Walls, No Pattern)', options = '{"Tube Type": "2\" x 1\" x 0.035\"", "Pattern": "Plain"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:4cffa3f2a677' AND name = '2" x 1" SWYFT Tube (3,0 " L, 0.035" Walls, No Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 0.035\"", "Pattern": "Plain"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" SWYFT Tube (0.035" Walls, Grid Pattern)', options = '{"Tube Type": "2\" x 1\" x 0.035\"", "Pattern": "Grid"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:c761f11ee9d1' AND name = '2" x 1" SWYFT Tube (3,0 " L, 0.035" Walls, Grid Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 0.035\"", "Pattern": "Grid"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" SWYFT Tube (1/16" Walls, No Pattern)', options = '{"Tube Type": "2\" x 1\" x 1/16\"", "Pattern": "Plain"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:2931813eb745' AND name = '2" x 1" SWYFT Tube (3,0 " L, 1/16" Walls, No Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 1/16\"", "Pattern": "Plain"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" SWYFT Tube (1/16" Walls, Grid + Bearing Pattern)', options = '{"Tube Type": "2\" x 1\" x 1/16\"", "Pattern": "Grid + Bearing"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:48a56c939b28' AND name = '2" x 1" SWYFT Tube (3,0 " L, 1/16" Walls, Grid + Bearing Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 1/16\"", "Pattern": "Grid + Bearing"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" SWYFT Tube (1/8" Walls, No Pattern)', options = '{"Tube Type": "2\" x 1\" x 1/8\"", "Pattern": "Plain"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:3664ae3f498a' AND name = '2" x 1" SWYFT Tube (3,0 " L, 1/8" Walls, No Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 1/8\"", "Pattern": "Plain"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" SWYFT Tube (1/8" Walls, Grid Pattern)', options = '{"Tube Type": "2\" x 1\" x 1/8\"", "Pattern": "Grid"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:f8b33244a370' AND name = '2" x 1" SWYFT Tube (3,0 " L, 1/8" Walls, Grid Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 1/8\"", "Pattern": "Grid"}';
-- (no part number): no vendor listing
UPDATE catalog_items SET name = '2" x 1" SWYFT Tube (1/8" Walls, Grid + Bearing Pattern)', options = '{"Tube Type": "2\" x 1\" x 1/8\"", "Pattern": "Grid + Bearing"}' WHERE source_id = '657896a4-bb1b-4cce-b532-3f54ac552922:f74c0576312a' AND name = '2" x 1" SWYFT Tube (3,0 " L, 1/8" Walls, Grid + Bearing Pattern)' AND options = '{"Tube Type": "2\" x 1\" x 1/8\"", "Pattern": "Grid + Bearing"}';
-- TTB-0094: Thrifty 2" x 1" Grid Pattern Aluminum Box Extrusion .125" Wall Thickness
UPDATE catalog_items SET name = '2" x 1" x 0.125" Aluminum Box Tube (Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Hole Offset": "0.5 inch"}' WHERE source_id = 'ba78467b-8454-43b1-a47e-1aa5f0cf798f:30cebb29e61f' AND name = '2" x 1" x 0.125" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Hole Offset": "0.5 inch", "Length": "3 inch"}';
-- WCP-0895: 2" x 1" x 0.062" Aluminum Tube Stock 2" Pattern (47")
UPDATE catalog_items SET name = '2" x 1" x 0.0625" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.0625\"", "Pattern Type": "Full"}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:da5f0a55a8c3' AND name = '2" x 1" x 0.0625" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.0625\"", "Pattern Type": "Full"}';
-- WCP-0894: 2" x 1" x 0.062" Aluminum Tube Stock 1" Pattern (47")
UPDATE catalog_items SET name = '2" x 1" x 0.0625" Aluminum Box Tube (47" L, Top Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.0625\"", "Pattern Type": "Top"}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:b7b668ba8edd' AND name = '2" x 1" x 0.0625" Aluminum Box Tube (3" L, Top Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.0625\"", "Pattern Type": "Top"}';
-- WCP-1428: 2" x 1" x 0.093" Aluminum Tube Stock 2" Pattern (47")
UPDATE catalog_items SET name = '2" x 1" x 0.09375" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.09375\"", "Pattern Type": "Full"}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:c0d7b4afa4df' AND name = '2" x 1" x 0.09375" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.09375\"", "Pattern Type": "Full"}';
-- WCP-1427: 2" x 1" x 0.093" Aluminum Tube Stock 1" Pattern (47")
UPDATE catalog_items SET name = '2" x 1" x 0.09375" Aluminum Box Tube (47" L, Top Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.09375\"", "Pattern Type": "Top"}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:5d1a200a52f7' AND name = '2" x 1" x 0.09375" Aluminum Box Tube (3" L, Top Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.09375\"", "Pattern Type": "Top"}';
-- WCP-1025: 2" x 1" x 0.125" Aluminum Tube Stock 2" Pattern (47")
UPDATE catalog_items SET name = '2" x 1" x 0.125" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Pattern Type": "Full"}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:935aaceccf5d' AND name = '2" x 1" x 0.125" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Pattern Type": "Full"}';
-- WCP-1024: 2" x 1" x 0.125" Aluminum Tube Stock 1" Pattern (47")
UPDATE catalog_items SET name = '2" x 1" x 0.125" Aluminum Box Tube (47" L, Top Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Pattern Type": "Top"}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:33603af22ace' AND name = '2" x 1" x 0.125" Aluminum Box Tube (3" L, Top Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 1\" x 0.125\"", "Pattern Type": "Top"}';
-- WCP-0924: 1" x 1" x 0.062" Aluminum Tube Stock with Hole Pattern (47")
UPDATE catalog_items SET name = '1" x 1" x 0.0625" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1\" x 1\" x 0.0625\""}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:fea852950e20' AND name = '1" x 1" x 0.0625" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1\" x 1\" x 0.0625\""}';
-- WCP-1586: 1" x 1" x 0.093" Aluminum Tube Stock with Hole Pattern (47")
UPDATE catalog_items SET name = '1" x 1" x 0.0625" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1\" x 1\" x 0.09375\""}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:7d0a3a893349' AND name = '1" x 1" x 0.0625" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1\" x 1\" x 0.09375\""}';
-- WCP-1023: 1" x 1" x 0.125" Aluminum Tube Stock with Hole Pattern (47")
UPDATE catalog_items SET name = '1" x 1" x 0.125" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "1\" x 1\" x 0.125\""}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:2b8056e8f3e9' AND name = '1" x 1" x 0.125" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "1\" x 1\" x 0.125\""}';
-- WCP-0926: 2" x 2" x 0.062" Aluminum Tube Stock with Hole Pattern (47")
UPDATE catalog_items SET name = '2" x 2" x 0.0625" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 2\" x 0.0625\""}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:2ebe12e09d46' AND name = '2" x 2" x 0.0625" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 2\" x 0.0625\""}';
-- WCP-1587: 2" x 2" x 0.093" Aluminum Tube Stock with Hole Pattern (47")
UPDATE catalog_items SET name = '2" x 2" x 0.093" Aluminum Box Tube (47" L, Full Pattern, 0.5" Pitch)', options = '{"Tube Type": "2\" x 2\" x 0.093\""}' WHERE source_id = '80ae48ea-9c15-4ff2-93d2-8a08bc2877e9:2f036f3ddb16' AND name = '2" x 2" x 0.093" Aluminum Box Tube (3" L, Full Pattern, 0.5" Pitch)' AND options = '{"Tube Type": "2\" x 2\" x 0.093\""}';
-- WCP-0931: 1" x 1" x 1" x 2.5mm Aluminum C-Channel with Hole Pattern (47")
UPDATE catalog_items SET name = 'Aluminum C-Channel 1" x 1" x  1" x 0.090" (47" L)', options = '{"Type": "1\" x 1\" x 1\" x 0.090\"", "Hole Offset": "0.5 inch", "Length": "47\""}' WHERE source_id = '3ff38c03-13d4-4762-9bc5-f62b6b4311b4:254f0b876919' AND name = 'Aluminum C-Channel 1" x 1" x  1" x 0.090" (2" L)' AND options = '{"Type": "1\" x 1\" x 1\" x 0.090\"", "Length": "2 inch", "Hole Offset": "0.5 inch"}';
-- WCP-0932: 1" x 2" x 1" x 2.5mm Aluminum C-Channel with Hole Pattern (47")
UPDATE catalog_items SET name = 'Aluminum C-Channel 1" x 2" x 1" x 0.090" (47" L)', options = '{"Type": "1\" x 2\" x 1\" x 0.090\"", "Hole Offset": "0.5 inch", "Length": "47\""}' WHERE source_id = '3ff38c03-13d4-4762-9bc5-f62b6b4311b4:c4a68205ea66' AND name = 'Aluminum C-Channel 1" x 2" x 1" x 0.090" (2" L)' AND options = '{"Type": "1\" x 2\" x 1\" x 0.090\"", "Length": "2 inch", "Hole Offset": "0.5 inch"}';
-- REV-21-1000: 1in Extrusion - 4ft (REV-21-1000) 1in Extrusion - 4ft - Clear Anodized
UPDATE catalog_items SET name = '1" Aluminum Extrusion (48" L, Clear Anodized)', options = '{"Color": "Clear Anodized"}' WHERE source_id = 'cceea3eb-7739-48e8-9022-eba297e51aa7:a478ca9ad727' AND name = '1" Aluminum Extrusion (2" L, Clear Anodized)' AND options = '{"Color": "Clear Anodized"}';
-- REV-21-1404: 1in Extrusion - 4ft (REV-21-1404) 1in Extrusion - 4ft - Black Anodized
UPDATE catalog_items SET name = '1" Aluminum Extrusion (48" L, Black Anodized)', options = '{"Color": "Black Anodized"}' WHERE source_id = 'cceea3eb-7739-48e8-9022-eba297e51aa7:2072ff32b19d' AND name = '1" Aluminum Extrusion (2" L, Black Anodized)' AND options = '{"Color": "Black Anodized"}';
-- am-5354: no vendor listing
UPDATE catalog_items SET name = '0.75" ID x 0.875" OD Aluminum Round Tube', options = '{"Tube Type": "0.75\" ID x 0.875\" OD"}' WHERE source_id = 'c695e1d6-d1b6-4b9d-805f-c0c48152d2cd:0f506807e9d5' AND name = '0.75" ID x 0.875" OD Aluminum Round Tube (1" L)' AND options = '{"Tube Type": "0.75\" ID x 0.875\" OD", "Length": "1 inch"}';
-- REV-21-2510: Dead Axle Tube - 3/4in - 36in 
UPDATE catalog_items SET name = '0.625" ID x 0.75" OD Aluminum Round Tube (36" L)', options = '{"Tube Type": "0.625\" ID x 0.75\" OD", "Length": "36\""}' WHERE source_id = '5dcde8f8-1142-46cf-b9b2-01dc8de0d11a:10e18f8e0972' AND name = '0.625" ID x 0.75" OD Aluminum Round Tube (1" L)' AND options = '{"Tube Type": "0.625\" ID x 0.75\" OD", "Length": "1 inch"}';
-- WCP-1269: 0.75" OD x .625" ID Aluminum Round Tube Stock (47")
UPDATE catalog_items SET name = '0.625" ID x 0.75" OD Aluminum Round Tube (47" L)', options = '{"Type": "0.625\" ID x 0.75\" OD"}' WHERE source_id = '175613b4-c275-4f33-878b-ea4af1386056:612a08014585' AND name = '0.625" ID x 0.75" OD Aluminum Round Tube (1" L)' AND options = '{"Type": "0.625\" ID x 0.75\" OD"}';
-- WCP-0910: .375" OD x .196" ID Aluminum Round Tube Stock (36")
UPDATE catalog_items SET name = '0.196" ID x 0.375" OD Aluminum Round Tube (36" L)', options = '{"Type": "0.196\" ID x .375\" OD"}' WHERE source_id = '175613b4-c275-4f33-878b-ea4af1386056:475a8eb60f62' AND name = '0.196" ID x 0.375" OD Aluminum Round Tube (1" L)' AND options = '{"Type": "0.196\" ID x .375\" OD"}';
-- WCP-0913: .500" OD x .196" ID Aluminum Round Tube Stock (36")
UPDATE catalog_items SET name = '0.196" ID x 0.5" OD Aluminum Round Tube (36" L)', options = '{"Type": "0.196\" ID x .5\" OD"}' WHERE source_id = '175613b4-c275-4f33-878b-ea4af1386056:d5b22dbdf0fc' AND name = '0.196" ID x 0.5" OD Aluminum Round Tube (1" L)' AND options = '{"Type": "0.196\" ID x .5\" OD"}';
-- WCP-1142: .75" OD x .500" Hex ID Aluminum Round Tube Stock (36")
UPDATE catalog_items SET name = '0.5" Hex ID x 0.75" OD Aluminum Round Tube (36" L)', options = '{"Type": "0.5\" Hex ID x 0.75\" OD"}' WHERE source_id = '175613b4-c275-4f33-878b-ea4af1386056:f541d788f3bb' AND name = '0.5" Hex ID x 0.75" OD Aluminum Round Tube (1" L)' AND options = '{"Type": "0.5\" Hex ID x 0.75\" OD"}';
-- WCP-1270: 1" OD x .875" ID Aluminum Round Tube Stock (47")
UPDATE catalog_items SET name = '0.875" ID x 1" OD Aluminum Round Tube (47" L)', options = '{"Type": "0.875\" ID x 1\" OD"}' WHERE source_id = '175613b4-c275-4f33-878b-ea4af1386056:212933ad6d8d' AND name = '0.875" ID x 1" OD Aluminum Round Tube (1" L)' AND options = '{"Type": "0.875\" ID x 1\" OD"}';
-- WCP-1271: 1.25" OD x 1.125" ID Aluminum Round Tube Stock (47")
UPDATE catalog_items SET name = '1.125" ID x 1.25" OD Aluminum Round Tube (47" L)', options = '{"Type": "1.125\" ID x 1.25\" OD"}' WHERE source_id = '175613b4-c275-4f33-878b-ea4af1386056:64a1fd71d2fe' AND name = '1.125" ID x 1.25" OD Aluminum Round Tube (1" L)' AND options = '{"Type": "1.125\" ID x 1.25\" OD"}';
-- TTB-314: no vendor listing
UPDATE catalog_items SET name = 'Thrifty Bumper Foam (Chamfer Edges)', options = '{}' WHERE source_id = 'fd52acd7-3f6a-4354-a6d9-3f2d1e090d53:e5a15429b1d5' AND name = 'Thrifty Bumper Foam (5" L, Chamfer Edges)' AND options = '{"Length": "5 inch"}';
-- WCP-2497: Sharp Corner Crosslinked Polyethylene Bumper Foam (3lb, 2.5" x 5" x 36")
UPDATE catalog_items SET name = 'WCP Bumper Foam (36" L, Sharp Edges)', options = '{"Type": "Sharp Corners"}' WHERE source_id = 'b483fb75-ee3c-42c2-a3b1-ffb28e78fc1f:16076bf6cdc4' AND name = 'WCP Bumper Foam (5" L, Sharp Edges)' AND options = '{"Type": "Sharp Corners"}';
-- am-2291: 0.5 in. Hex 7075 Aluminum Shaft Stock 1 ft.
UPDATE catalog_items SET name = '1/2" Hex (7075 Aluminum)', options = '{"Type": "1/2\" Hex (7075 Aluminum)"}' WHERE source_id = '01390a1f-8a44-4205-98ca-f454efaecf40:b4e0e3357ef2' AND name = '1/2" Hex (1" L, 7075 Aluminum)' AND options = '{"Type": "1/2\" Hex (7075 Aluminum)"}';
-- am-0856: no vendor listing
UPDATE catalog_items SET name = '1/2" Hex (1018 Steel)', options = '{"Type": "1/2\" Hex (1018 Steel)"}' WHERE source_id = '01390a1f-8a44-4205-98ca-f454efaecf40:2a4c270bd3c9' AND name = '1/2" Hex (1" L, 1018 Steel)' AND options = '{"Type": "1/2\" Hex (1018 Steel)"}';
-- am-3101: no vendor listing
UPDATE catalog_items SET name = '1/2" Churro (6061 Aluminum)', options = '{"Type": "1/2\" Churro (6061 Aluminum)"}' WHERE source_id = '01390a1f-8a44-4205-98ca-f454efaecf40:3a5360747e4c' AND name = '1/2" Churro (1" L, 6061 Aluminum)' AND options = '{"Type": "1/2\" Churro (6061 Aluminum)"}';
-- am-3807: 3/8 in. Hex 7075 Aluminum Shaft Stock 1 ft.
UPDATE catalog_items SET name = '3/8" Hex (7075 Aluminum)', options = '{"Type": "3/8\" Hex (7075 Aluminum)"}' WHERE source_id = '01390a1f-8a44-4205-98ca-f454efaecf40:aa3c505a1d66' AND name = '3/8" Hex (1" L, 7075 Aluminum)' AND options = '{"Type": "3/8\" Hex (7075 Aluminum)"}';
-- am-2356: 3/8 in. Steel Hex Shaft Stock 1.85 in.
UPDATE catalog_items SET name = '3/8" Hex (1018 Steel)', options = '{"Type": "3/8\" Hex (1018 Steel)"}' WHERE source_id = '01390a1f-8a44-4205-98ca-f454efaecf40:a935910db1a4' AND name = '3/8" Hex (1" L, 1018 Steel)' AND options = '{"Type": "3/8\" Hex (1018 Steel)"}';
-- am-3101: no vendor listing
UPDATE catalog_items SET name = '3/8" Churro (6061 Aluminum)', options = '{"Type": "3/8\" Churro (6061 Aluminum)"}' WHERE source_id = '01390a1f-8a44-4205-98ca-f454efaecf40:4befddfd35b4' AND name = '3/8" Churro (1" L, 6061 Aluminum)' AND options = '{"Type": "3/8\" Churro (6061 Aluminum)"}';
-- REV-21-1135: 1/2in Rounded Hex Shafts (REV-21-1135) 1/2in Rounded Hex Shaft - 36.0in (not tapped)
UPDATE catalog_items SET name = '1/2" Rounded Hex (36" L, 13.75mm OD)', options = '{"Type": "1/2\" Rounded Hex (13.75mm OD)"}' WHERE source_id = '28f525a5-293e-4d21-a96a-7188570ca9a7:e40f1e80382c' AND name = '1/2" Rounded Hex (1" L, 13.75mm OD)' AND options = '{"Type": "1/2\" Rounded Hex (13.75mm OD)"}';
-- REV-41-3205: Rounded UltraHex Shaft - 36in Long 
UPDATE catalog_items SET name = '1/2" Rounded UltraHex (36" L, 13.75mm OD)', options = '{"Type": "1/2\" Rounded UltraHex (13.75mm OD)"}' WHERE source_id = '28f525a5-293e-4d21-a96a-7188570ca9a7:38c949c347e3' AND name = '1/2" Rounded UltraHex (1" L, 13.75mm OD)' AND options = '{"Type": "1/2\" Rounded UltraHex (13.75mm OD)"}';
-- SR-AXLE-HEX-0.5in-36in-AL7075: SR AXLE HEX 0.5in 36in AL7075
UPDATE catalog_items SET name = '1/2" Rounded Hex (36" L, 13.75mm OD, 7075 Aluminum)', options = '{"Material": "7075 Aluminum"}' WHERE source_id = 'b3444102-0a09-45f7-8530-38329000c548:a432cbd9d03a' AND name = '1/2" Rounded Hex (1" L, 13.75mm OD, 7075 Aluminum)' AND options = '{"Material": "7075 Aluminum"}';
-- SR-AXLE-HEXtoSPLINE-0.5in-36in-AL6061: SR AXLE HEXtoSPLINE 0.5in 36in AL6061
UPDATE catalog_items SET name = '1/2" Rounded Hex (36" L, 13.75mm OD, 6061 Aluminum)', options = '{"Material": "6061 Aluminum"}' WHERE source_id = 'b3444102-0a09-45f7-8530-38329000c548:6762287562e9' AND name = '1/2" Rounded Hex (1" L, 13.75mm OD, 6061 Aluminum)' AND options = '{"Material": "6061 Aluminum"}';
-- TTB-0069: QTY 1 - 36 Inch Long 1/2" Rounded Hex Shaft - 7075 Aluminum
UPDATE catalog_items SET name = '1/2" Rounded Hex (36" L, 13.75mm OD, 7075)', options = '{"Type": "1/2\" Rounded Hex (13.75mm OD, 7075)"}' WHERE source_id = 'b479ffef-9940-400e-ba52-6828042f6b5f:913a8c055e4a' AND name = '1/2" Rounded Hex (1" L, 13.75mm OD, 7075)' AND options = '{"Type": "1/2\" Rounded Hex (13.75mm OD, 7075)"}';
-- TTB-0068: QTY 1 - 36 Inch Long 1/2" Rounded Hex Shaft - 6061 Aluminum
UPDATE catalog_items SET name = '1/2" Rounded Hex (36" L, 13.75mm OD, 6061)', options = '{"Type": "1/2\" Rounded Hex (13.75mm OD, 6061)"}' WHERE source_id = 'b479ffef-9940-400e-ba52-6828042f6b5f:9ecb60ea8295' AND name = '1/2" Rounded Hex (1" L, 13.75mm OD, 6061)' AND options = '{"Type": "1/2\" Rounded Hex (13.75mm OD, 6061)"}';
-- WCP-0914: .500" OD x .159" ID Rounded Hex Stock (36")
UPDATE catalog_items SET name = '1/2" Rounded Hex (36" L, 13.75mm OD)', options = '{"Type": "1/2\" Rounded Hex (13.75mm OD)", "Length": "36\""}' WHERE source_id = '4af0bf23-0a30-48ac-ad63-795853541439:5d6053a5703b' AND name = '1/2" Rounded Hex (1" L, 13.75mm OD)' AND options = '{"Type": "1/2\" Rounded Hex (13.75mm OD)", "Length": "1 inch"}';
-- WCP-0911: .375" OD x .159" ID Rounded Hex Stock (36")
UPDATE catalog_items SET name = '3/8" Rounded Hex (36" L, 10.25mm OD)', options = '{"Type": "3/8\" Rounded Hex (10.25mm OD)", "Length": "36\""}' WHERE source_id = '4af0bf23-0a30-48ac-ad63-795853541439:b0c5626b98e1' AND name = '3/8" Rounded Hex (1" L, 10.25mm OD)' AND options = '{"Type": "3/8\" Rounded Hex (10.25mm OD)", "Length": "1 inch"}';
-- WCP-0915: .500" OD Hex Stock (36")
UPDATE catalog_items SET name = '1/2" Hex (36" L)', options = '{"Type": "1/2\" Hex", "Length": "36\""}' WHERE source_id = '4af0bf23-0a30-48ac-ad63-795853541439:abe8020719a6' AND name = '1/2" Hex (1" L)' AND options = '{"Type": "1/2\" Hex", "Length": "1 inch"}';
-- WCP-0912: .375" OD Hex Stock (36")
UPDATE catalog_items SET name = '3/8" Hex (36" L)', options = '{"Type": "3/8\" Hex", "Length": "36\""}' WHERE source_id = '4af0bf23-0a30-48ac-ad63-795853541439:4977cca1f83d' AND name = '3/8" Hex (1" L)' AND options = '{"Type": "3/8\" Hex", "Length": "1 inch"}';
-- WCP-0917: .500" OD Hex Lite Stock (36")
UPDATE catalog_items SET name = '1/2" Hex Lite (36" L)', options = '{"Type": "1/2\" Hex Lite", "Length": "36\""}' WHERE source_id = '4af0bf23-0a30-48ac-ad63-795853541439:46783371f8b3' AND name = '1/2" Hex Lite (1" L)' AND options = '{"Type": "1/2\" Hex Lite", "Length": "1 inch"}';
-- WCP-1418: .375" OD Hex Lite Stock (36")
UPDATE catalog_items SET name = '3/8" Hex Lite (36" L)', options = '{"Type": "3/8\" Hex Lite", "Length": "36\""}' WHERE source_id = '4af0bf23-0a30-48ac-ad63-795853541439:6916b620f169' AND name = '3/8" Hex Lite (1" L)' AND options = '{"Type": "3/8\" Hex Lite", "Length": "1 inch"}';
-- SR-AXLE-SPLINE-15T-450mm-SS304: SR AXLE SPLINE 15T 450mm SS304
UPDATE catalog_items SET name = '15T Spline Shaft (450mm L, 8mm OD, 304 Stainless Steel)', options = '{"Material": "304 Stainless Steel"}' WHERE source_id = '43b25b81-bac8-4835-be0d-9d1a6968a974:236eeb70f443' AND name = '15T Spline Shaft (2" L, 8mm OD, 304 Stainless Steel)' AND options = '{"Material": "304 Stainless Steel"}';
-- SR-AXLE-SPLINE-15T-450mm-AL7075: SR AXLE SPLINE 15T 450mm AL7075
UPDATE catalog_items SET name = '15T Spline Shaft (450mm L, 8mm OD, 7075 Aluminum)', options = '{"Material": "7075 Aluminum"}' WHERE source_id = '43b25b81-bac8-4835-be0d-9d1a6968a974:c2a2a41e277d' AND name = '15T Spline Shaft (2" L, 8mm OD, 7075 Aluminum)' AND options = '{"Material": "7075 Aluminum"}';
-- REV-41-6457: 15T Spline Shaft - 480mm 
UPDATE catalog_items SET name = '15t SplineXS Shaft (480mm L)', options = '{"Length": "480mm"}' WHERE source_id = 'f09559da-b232-49c8-bf87-570bc2651562:0eef7d056d3c' AND name = '15t SplineXS Shaft (1" L)' AND options = '{"Length": "1 inch"}';
-- REV-21-2520: MAXSpline Shafts - 47in MAXSpline Shaft - 47in (REV-21-2520)
UPDATE catalog_items SET name = 'MAXSpline (47" L)', options = '{"Length": "47\""}' WHERE source_id = '48dcf27f-fa83-4df5-b741-146be3c2a376:750c81fd0eeb' AND name = 'MAXSpline (1" L)' AND options = '{"Length": "1 inch"}';
-- WCP-0918: SplineXL Tube Stock (47" L, 1" Bore)
UPDATE catalog_items SET name = 'SplineXL (47" L)', options = '{"Length": "47\""}' WHERE source_id = '27af9c84-51d2-4852-bae7-a8183b785b9a:65a5a7c2f0c3' AND name = 'SplineXL (1" L)' AND options = '{"Length": "1 inch"}';
