"""Builds the catalog seed migration from the FRCDesign library export (run once).

    python3 -m pip install openpyxl
    python3 workers/orders/scripts/catalog-seed.py frc-ordering-catalog.xlsx \
        > workers/orders/src/db/migrations/0010_catalog_seed.sql

Rows without a purchase link, custom-made parts, family placeholders and VEXpro parts (VEX no
longer sells FRC parts) are left out.
"""

import json
import sys
import time
from urllib.parse import urlparse

import openpyxl

# Same names as workers/orders/src/lib/vendors.ts, so catalog items and requests match.
VENDOR_FOR_HOST = {"8020.net": "80/20"}


def product_key(url: str) -> str:
    """workers/orders/src/routes/fast-entry.ts productKey(), for product links."""
    u = urlparse(url)
    host = (u.hostname or "").lower().removeprefix("www.")
    return f"{host}{u.path.rstrip('/').lower()}"


def sql(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def options_of(config: str) -> dict:
    out = {}
    for part in (config or "").split("; "):
        key, sep, value = part.partition(": ")
        if sep and key != "Vendor":
            out[key.strip()] = value.strip()
    return out


def item_name(full: str, vendor: str) -> str:
    name = full.split(" — ")[0]
    suffix = f" ({vendor})"
    return name[: -len(suffix)] if name.endswith(suffix) else name


def main(path: str):
    rows = list(openpyxl.load_workbook(path, read_only=True)["Catalog"].iter_rows(values_only=True))
    header = rows[0]
    records = [dict(zip(header, r)) for r in rows[1:]]
    now = int(time.time() * 1000)

    families = {}
    items = []
    for r in records:
        url = r["Purchase / vendor link"]
        if (
            r["Record type"] != "Published catalog record"
            or not url
            or r["Vendor"] in ("Custom", "VEXpro")
        ):
            continue
        family_id = r["Record ID"].split(":")[0]
        families.setdefault(
            family_id, (r["Part family"], r["Category"], r["FRC Design source"])
        )
        vendor = VENDOR_FOR_HOST.get(urlparse(url).hostname or "", r["Vendor"])
        kind = {
            "Vendor link (source)": "product",
            "Vendor SKU search (source)": "search",
        }.get(r["Link type"], "homepage")
        sku = r["Part number"]
        items.append(
            {
                "family": family_id,
                "category": r["Category"],
                "name": item_name(r["Name with configuration"], r["Vendor"]),
                "vendor": vendor,
                "sku": sku,
                "options": json.dumps(options_of(r["Configuration"]), ensure_ascii=False),
                "url": url,
                "kind": kind,
                "key": product_key(url) if kind == "product" else None,
                "source_id": r["Record ID"],
            }
        )

    print("-- Generated by workers/orders/scripts/catalog-seed.py from the FRCDesign library export.")
    print(f"-- {len(families)} families, {len(items)} items.")
    fam = list(families.items())
    for i in range(0, len(fam), 50):
        values = ",\n".join(
            f"({sql(name)}, {sql(cat)}, {sql(fid)}, {sql(src)}, {now})"
            for fid, (name, cat, src) in fam[i : i + 50]
        )
        print(
            "INSERT INTO catalog_families (name, category, source_id, source_url, created_at) VALUES\n"
            + values
            + ";"
        )
    for i in range(0, len(items), 50):
        values = ",\n".join(
            f"((SELECT id FROM catalog_families WHERE source_id = {sql(it['family'])}), "
            f"{sql(it['category'])}, {sql(it['name'])}, {sql(it['vendor'])}, {sql(it['sku'])}, "
            f"{sql(it['options'])}, {sql(it['url'])}, {sql(it['kind'])}, {sql(it['key'])}, "
            f"'frcdesign', {sql(it['source_id'])}, {now}, {now})"
            for it in items[i : i + 50]
        )
        print(
            "INSERT INTO catalog_items (family_id, category, name, vendor, sku, options, url, "
            "link_kind, product_key, source, source_id, created_at, updated_at) VALUES\n"
            + values
            + ";"
        )


if __name__ == "__main__":
    main(sys.argv[1])
